static_library("iter1_line_follow_diagnostic") {
    sources = [
        "iter1_line_follow_diagnostic.c",
        "iter1_line_follow_fsm.c",
    ]

    include_dirs = [
        "//utils/native/lite/include",
        "//kernel/liteos_m/components/cmsis/2.0",
        "//base/iot_hardware/interfaces/kits/wifiiot_lite",
        ".",
    ]
}
